# Generated by Django 4.1.1 on 2022-09-15 06:33

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0076_modellogentry_revision"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("heading", models.CharField(max_length=255)),
                ("date", models.DateTimeField(auto_now=True)),
                ("author", models.CharField(max_length=100)),
                ("body", wagtail.fields.RichTextField()),
            ],
            options={"abstract": False,},
            bases=("wagtailcore.page",),
        ),
    ]
